//首页模块
const PAGE_HOME = '/front-home'

// 购物车模块
const PAGE_SHOPPING_CART = '/front-shopping-cart'

// 登录注册模块
const PAGE_MEMBER = '/front-member'

// 订单模块
const PAGE_ORDER = '/front-order'

// 搜索模块
const PAGE_SEARCH = '/front-search'

// 地址模块
const PAGE_ADDRESS = '/front-address'
const PAGE_ADDRESS_LIST = PAGE_ADDRESS + '/list'
const PAGE_ADDRESS_ADD_ADDRESS = PAGE_ADDRESS + '/add-address'
const PAGE_ADDRESS_EXPRESS_LIST = PAGE_ADDRESS + '/express-list'
const PAGE_ADDRESS_ADD_EXPRESS = PAGE_ADDRESS + '/add-express'
const PAGE_ADDRESS_LOGISTICS_INFORMATION =
  PAGE_ADDRESS + '/logistics-information'

// 商品模块
const PAGE_COMMODITY = '/front-commodity'
const PAGE_COMMODITY_LIST = PAGE_COMMODITY + '/list'
const PAGE_COMMODITY_ACCOUNTS = PAGE_COMMODITY + '/accounts'
const PAGE_COMMODITY_DETAIL = PAGE_COMMODITY + '/detail'
const PAGE_COMMODITY_COMMENT = PAGE_COMMODITY + '/comment'

// 优惠券模块
const PAGE_COUPON = '/front-coupon'
const PAGE_COUPON_CENTER = PAGE_COUPON + '/center'
const PAGE_COUPON__DISCOUNT_COUPON = PAGE_COUPON + '/discount-coupon'

// 个人中心模块
const PAGE_PROFILE = '/front-profile'
const PAGE_PROFILE_INDEX = PAGE_PROFILE + '/index'
const PAGE_PROFILE_COLLECTING = PAGE_PROFILE + '/collecting'
const PAGE_PROFILE_HELP_CENTER = PAGE_PROFILE + '/help-center'
const PAGE_PROFILE_MESSAGE_CENTER = PAGE_PROFILE + '/message-center'
const PAGE_PROFILE_MESSAGE_MANAGEMENT = PAGE_PROFILE + '/message-management'
const PAGE_PROFILE_PASSWORD_MANAGEMENT = PAGE_PROFILE + '/password-management'
const PAGE_PROFILE_SECURITY_CENTER = PAGE_PROFILE + '/security-center'
const PAGE_PROFILE_SHARE_FRIENDS = PAGE_PROFILE + '/share-friends'
const PAGE_PROFILE_USER_INFO = PAGE_PROFILE + '/user-info'

// 钱包模块
const PAGE_WALLET = '/front-wallet'
const PAGE_WALLET_MY_WALLET = PAGE_WALLET + '/my-wallet'
const PAGE_WALLET_ADD_BANK_CARD = PAGE_WALLET + '/add-bank-card'
const PAGE_WALLET_ELECTRONIC_LIST = PAGE_WALLET + '/electronic-list'
const PAGE_WALLET_RECHARGE_WALLET = PAGE_WALLET + '/recharge-wallet'
const PAGE_WALLET_RECORD_DETAIL = PAGE_WALLET + '/record-detail'
const PAGE_WALLET_RECORD_LIST = PAGE_WALLET + '/record-list'

// 404 页面
const PAGE_NOT_FOUNT = '*'

export {
  PAGE_ADDRESS,
  PAGE_ADDRESS_ADD_ADDRESS,
  PAGE_ADDRESS_EXPRESS_LIST,
  PAGE_ADDRESS_LOGISTICS_INFORMATION,
  PAGE_ADDRESS_ADD_EXPRESS,
  PAGE_ADDRESS_LIST,
  PAGE_COMMODITY,
  PAGE_COMMODITY_ACCOUNTS,
  PAGE_COMMODITY_COMMENT,
  PAGE_COMMODITY_DETAIL,
  PAGE_COMMODITY_LIST,
  PAGE_COUPON,
  PAGE_COUPON_CENTER,
  PAGE_COUPON__DISCOUNT_COUPON,
  PAGE_HOME,
  PAGE_MEMBER,
  PAGE_NOT_FOUNT,
  PAGE_ORDER,
  PAGE_PROFILE,
  PAGE_PROFILE_INDEX,
  PAGE_PROFILE_COLLECTING,
  PAGE_PROFILE_HELP_CENTER,
  PAGE_PROFILE_MESSAGE_CENTER,
  PAGE_PROFILE_MESSAGE_MANAGEMENT,
  PAGE_PROFILE_PASSWORD_MANAGEMENT,
  PAGE_PROFILE_SECURITY_CENTER,
  PAGE_PROFILE_SHARE_FRIENDS,
  PAGE_PROFILE_USER_INFO,
  PAGE_SEARCH,
  PAGE_SHOPPING_CART,
  PAGE_WALLET,
  PAGE_WALLET_ADD_BANK_CARD,
  PAGE_WALLET_ELECTRONIC_LIST,
  PAGE_WALLET_MY_WALLET,
  PAGE_WALLET_RECHARGE_WALLET,
  PAGE_WALLET_RECORD_DETAIL,
  PAGE_WALLET_RECORD_LIST
}
